---
- name: Update NAP Config
  hosts: nginx
  gather_facts: no
  become: yes

  tasks:
  - name: "Ensure NGINX WAF Policy Directory Exists"
    file:
      path: "{{ nginx_main_upload_dest | default('/etc/nginx/appprotect/waf-policy') }}"
      state: directory

  - name: "Upload NGINX Updated WAF Policy - f1-api"
    copy:
      src: "{{ nginx_main_upload_src | default('f1-waf-policy.json') }}"
      dest: "{{ nginx_main_upload_dest | default('/etc/nginx/appprotect/waf-policy') }}"
      backup: no
      
  - name: "Upload NGINX Updated WAF Policy - Default Policy"
    copy:
      src: "{{ nginx_main_upload_src | default('NginxDefaultPolicy.json') }}"
      dest: "{{ nginx_main_upload_dest | default('/etc/nginx/appprotect/waf-policy') }}"
      backup: no
      
  - name: "Upload NGINX Configuration File"
    copy:
      src: "{{ nginx_main_upload_src | default('nginx.conf') }}"
      dest: "{{ nginx_main_upload_dest | default('/etc/nginx') }}"
      backup: no

  - name: "Reload NGINX"
    command: "/usr/sbin/nginx -s reload"
